# Generated by Django 3.1.5 on 2021-01-26 08:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('velox_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=40)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=13, region=None)),
                ('resume', models.FileField(upload_to='resumes')),
                ('appliedOn', models.DateField(default=datetime.datetime(2021, 1, 26, 8, 11, 0, 559598, tzinfo=utc))),
            ],
        ),
        migrations.RemoveField(
            model_name='careersopportunity',
            name='salary',
        ),
        migrations.AlterField(
            model_name='careersopportunity',
            name='createdOn',
            field=models.DateField(default=datetime.datetime(2021, 1, 26, 8, 11, 0, 476170, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='careersopportunity',
            name='skills',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
