# Generated by Django 3.1.5 on 2021-01-26 08:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('velox_app', '0002_auto_20210126_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='careersopportunity',
            name='salary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='appliedOn',
            field=models.DateField(default=datetime.datetime(2021, 1, 26, 8, 14, 4, 599374, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='careersopportunity',
            name='createdOn',
            field=models.DateField(default=datetime.datetime(2021, 1, 26, 8, 14, 4, 517128, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='careersopportunity',
            name='skills',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
