# Generated by Django 3.1.5 on 2021-01-26 08:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('velox_app', '0003_auto_20210126_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careersopportunity',
            name='salary',
        ),
        migrations.AlterField(
            model_name='applicant',
            name='appliedOn',
            field=models.DateField(default=datetime.datetime(2021, 1, 26, 8, 33, 9, 308592, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='careersopportunity',
            name='createdOn',
            field=models.DateField(default=datetime.datetime(2021, 1, 26, 8, 33, 9, 190069, tzinfo=utc)),
        ),
    ]
