# Generated by Django 3.1.3 on 2021-01-27 07:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('velox_app', '0004_auto_20210126_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('comment', models.TextField()),
                ('commentedOn', models.DateField(default=datetime.datetime(2021, 1, 27, 7, 27, 22, 56500, tzinfo=utc))),
            ],
        ),
        migrations.AlterField(
            model_name='applicant',
            name='appliedOn',
            field=models.DateField(default=datetime.datetime(2021, 1, 27, 7, 27, 22, 56500, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='careersopportunity',
            name='createdOn',
            field=models.DateField(default=datetime.datetime(2021, 1, 27, 7, 27, 22, 14819, tzinfo=utc)),
        ),
    ]
